---
- name: Add host to DSF inventory in Ansible Tower
  hosts: all
#  gather_facts: yes
  tasks:
    - name: Gather facts from the target host '{{ lookup("env", "DSF_NOTITY_TOKEN") }}'
      ansible.builtin.setup:

    - name: Convert variables to JSON string
      set_fact:
        host_variables_json: "{{ ansible_facts | to_json }}"

    
    - name: Add host to DSF Ansible Tower inventory
      uri:
        url: "http://128.140.77.1/api/v2/inventories/2/hosts/"
        method: POST
        body_format: json
        body:
          name: "{{ ansible_fqdn }}"
#          name: "test"
          description: "Automatically added host"
          variables: "{{ host_variables_json }}"
       #   variables: "{\"ansible_host\": \"127.0.0.1\"}"
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer WbhwSlEdEnzB4qPy7qVz6dWNcvtUSe"
        status_code: 201
        validate_certs: yes
      delegate_to: localhost
      register: response

    - debug: var=response
